import { collections } from '../config/mongodb';
import { Task } from '../types';

export const defaultTasks: Omit<Task, 'id' | 'createdBy' | 'createdAt' | 'updatedAt'>[] = [
  // Writing and Language tasks (语文)
  {
    title: '写日记',
    description: '完成一篇日记，记录今天的见闻和感受。每50字额外加1分',
    category: 'reading',
    difficulty: 'easy',
    estimatedTime: 20,
    points: 2,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['日记', '写作', '语文'],
    isPublic: true,
  },
  {
    title: '背诵古诗词',
    description: '背诵一首古诗词或现代诗歌，理解其含义',
    category: 'reading',
    difficulty: 'easy',
    estimatedTime: 20,
    points: 2,
    requiresEvidence: true,
    evidenceTypes: ['text', 'video'],
    tags: ['诗词', '背诵', '文学'],
    isPublic: true,
  },
  {
    title: '课外书阅读',
    description: '阅读课外书籍，每100页可获得2分奖励',
    category: 'reading',
    difficulty: 'easy',
    estimatedTime: 60,
    points: 2,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['阅读', '学习', '知识'],
    isPublic: true,
  },

  // Math and Learning tasks (数学)
  {
    title: '李永乐数学课程',
    description: '观看李永乐老师的数学视频课程并完成练习',
    category: 'learning',
    difficulty: 'medium',
    estimatedTime: 30,
    points: 2,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['数学', '视频课程', '学习'],
    isPublic: true,
  },
  {
    title: '奥数题挑战',
    description: '解决一道奥数题或拓展难题，每题1分',
    category: 'learning',
    difficulty: 'hard',
    estimatedTime: 30,
    points: 1,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['奥数', '挑战', '思维'],
    isPublic: true,
  },
  {
    title: '年级提前学习',
    description: '提前完成三年级课程，进入四年级内容学习',
    category: 'learning',
    difficulty: 'hard',
    estimatedTime: 60,
    points: 5,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['提前学习', '数学', '进度'],
    isPublic: true,
  },

  // English Learning tasks (英语)
  {
    title: 'Duolingo英语练习',
    description: '使用Duolingo完成英语学习关卡',
    category: 'learning',
    difficulty: 'easy',
    estimatedTime: 20,
    points: 2,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['英语', '游戏学习', 'Duolingo'],
    isPublic: true,
  },
  {
    title: 'RunFox口语练习',
    description: '使用RunFox进行英语口语对话练习',
    category: 'learning',
    difficulty: 'medium',
    estimatedTime: 25,
    points: 2,
    requiresEvidence: true,
    evidenceTypes: ['text', 'video'],
    tags: ['英语', '口语', '对话'],
    isPublic: true,
  },

  // Programming and DIY tasks (编程)
  {
    title: 'CodeMonkey编程游戏',
    description: '通过CodeMonkey游戏学习编程基础知识',
    category: 'creativity',
    difficulty: 'medium',
    estimatedTime: 30,
    points: 2,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'text'],
    tags: ['编程', '游戏', '逻辑思维'],
    isPublic: true,
  },
  {
    title: 'Scratch创意编程',
    description: '使用Scratch制作一个小游戏或动画作品',
    category: 'creativity',
    difficulty: 'medium',
    estimatedTime: 45,
    points: 3,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'video'],
    tags: ['Scratch', '编程', '创作'],
    isPublic: true,
  },
  {
    title: 'DIY遥控车项目',
    description: '参与遥控车的设计、组装和测试过程',
    category: 'creativity',
    difficulty: 'hard',
    estimatedTime: 120,
    points: 10,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'video', 'text'],
    tags: ['DIY', '遥控车', '工程'],
    isPublic: true,
  },

  // Music Practice tasks (音乐)
  {
    title: '钢琴练习',
    description: '练习钢琴15-30分钟，完成指定曲目',
    category: 'other',
    difficulty: 'medium',
    estimatedTime: 30,
    points: 1,
    requiresEvidence: true,
    evidenceTypes: ['video', 'text'],
    tags: ['钢琴', '音乐', '练习'],
    isPublic: true,
  },
  {
    title: '萨克斯练习',
    description: '练习萨克斯15-30分钟，学习新曲目',
    category: 'other',
    difficulty: 'medium',
    estimatedTime: 30,
    points: 1,
    requiresEvidence: true,
    evidenceTypes: ['video', 'text'],
    tags: ['萨克斯', '音乐', '练习'],
    isPublic: true,
  },

  // Exercise tasks
  {
    title: '晨练',
    description: '早上进行30分钟的体育锻炼，可以是跑步、做操或其他运动',
    category: 'exercise',
    difficulty: 'easy',
    estimatedTime: 30,
    points: 3,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'text'],
    tags: ['健康', '运动', '早晨'],
    isPublic: true,
  },
  {
    title: '游泳训练',
    description: '在游泳池或安全的水域进行1小时游泳训练',
    category: 'exercise',
    difficulty: 'medium',
    estimatedTime: 60,
    points: 30,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'video'],
    tags: ['游泳', '运动', '健康'],
    isPublic: true,
  },
  {
    title: '骑行探索',
    description: '骑自行车探索周边环境，锻炼身体同时欣赏风景',
    category: 'exercise',
    difficulty: 'medium',
    estimatedTime: 90,
    points: 40,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'text'],
    tags: ['骑行', '探索', '户外'],
    isPublic: true,
  },

  // Reading tasks
  {
    title: '阅读课外书',
    description: '阅读一本课外书籍至少30分钟，可以是小说、科普书或其他类型',
    category: 'reading',
    difficulty: 'easy',
    estimatedTime: 30,
    points: 20,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['阅读', '学习', '知识'],
    isPublic: true,
  },
  {
    title: '写读书笔记',
    description: '针对阅读的内容写一篇读书笔记，记录心得体会',
    category: 'reading',
    difficulty: 'medium',
    estimatedTime: 45,
    points: 25,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['阅读', '写作', '思考'],
    isPublic: true,
  },
  {
    title: '诗词背诵',
    description: '背诵一首古诗词或现代诗歌，理解其含义',
    category: 'reading',
    difficulty: 'easy',
    estimatedTime: 20,
    points: 15,
    requiresEvidence: true,
    evidenceTypes: ['text', 'video'],
    tags: ['诗词', '背诵', '文学'],
    isPublic: true,
  },

  // Chores tasks
  {
    title: '整理房间',
    description: '整理自己的房间，包括床铺、书桌和衣物收纳',
    category: 'chores',
    difficulty: 'easy',
    estimatedTime: 30,
    points: 10,
    requiresEvidence: true,
    evidenceTypes: ['photo'],
    tags: ['整理', '清洁', '责任'],
    isPublic: true,
  },
  {
    title: '帮助做饭',
    description: '协助家长准备一顿饭，学习基本的烹饪技能',
    category: 'chores',
    difficulty: 'medium',
    estimatedTime: 60,
    points: 25,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'video'],
    tags: ['烹饪', '家务', '技能'],
    isPublic: true,
  },
  {
    title: '清洁家居',
    description: '负责家中某个区域的清洁工作，如客厅、厨房或卫生间',
    category: 'chores',
    difficulty: 'medium',
    estimatedTime: 45,
    points: 20,
    requiresEvidence: true,
    evidenceTypes: ['photo'],
    tags: ['清洁', '家务', '责任'],
    isPublic: true,
  },

  // Learning tasks
  {
    title: '学习新技能',
    description: '学习一项新技能，如画画、编程、乐器等',
    category: 'learning',
    difficulty: 'hard',
    estimatedTime: 90,
    points: 50,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'video', 'text'],
    tags: ['技能', '学习', '成长'],
    isPublic: true,
  },
  {
    title: '复习学校课程',
    description: '复习学校的课程内容，巩固所学知识',
    category: 'learning',
    difficulty: 'medium',
    estimatedTime: 60,
    points: 30,
    requiresEvidence: true,
    evidenceTypes: ['text', 'photo'],
    tags: ['学习', '复习', '课程'],
    isPublic: true,
  },
  {
    title: '观看教育视频',
    description: '观看有教育意义的视频，如科学实验、历史纪录片等',
    category: 'learning',
    difficulty: 'easy',
    estimatedTime: 30,
    points: 15,
    requiresEvidence: true,
    evidenceTypes: ['text'],
    tags: ['教育', '视频', '知识'],
    isPublic: true,
  },

  // Creativity tasks
  {
    title: '绘画创作',
    description: '创作一幅画作，可以是素描、水彩或任何绘画形式',
    category: 'creativity',
    difficulty: 'medium',
    estimatedTime: 60,
    points: 35,
    requiresEvidence: true,
    evidenceTypes: ['photo'],
    tags: ['绘画', '创作', '艺术'],
    isPublic: true,
  },
  {
    title: '手工制作',
    description: '制作一件手工作品，如折纸、编织或其他手工艺品',
    category: 'creativity',
    difficulty: 'medium',
    estimatedTime: 75,
    points: 40,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'video'],
    tags: ['手工', '制作', '创意'],
    isPublic: true,
  },
  {
    title: '写作练习',
    description: '写一篇短文、日记或故事，发挥创造力',
    category: 'creativity',
    difficulty: 'medium',
    estimatedTime: 45,
    points: 25,
    requiresEvidence: true,
    evidenceTypes: ['text'],
    tags: ['写作', '创作', '表达'],
    isPublic: true,
  },

  // Other tasks
  {
    title: '社区服务',
    description: '参与社区服务活动，如环保活动、志愿服务等',
    category: 'other',
    difficulty: 'hard',
    estimatedTime: 120,
    points: 60,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'text'],
    tags: ['社区', '服务', '公益'],
    isPublic: true,
  },
  {
    title: '家庭时光',
    description: '与家人共度美好时光，如聊天、游戏或户外活动',
    category: 'other',
    difficulty: 'easy',
    estimatedTime: 60,
    points: 20,
    requiresEvidence: true,
    evidenceTypes: ['photo', 'text'],
    tags: ['家庭', '亲情', '互动'],
    isPublic: true,
  },
];

export const initializeDefaultTasks = async (systemUserId: string) => {
  try {
    console.log('Initializing default tasks...');
    
    for (const taskData of defaultTasks) {
      const task: Omit<Task, 'id'> = {
        ...taskData,
        createdBy: systemUserId,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
      
      await collections.tasks.add(task);
    }
    
    console.log(`Successfully initialized ${defaultTasks.length} default tasks`);
  } catch (error) {
    console.error('Error initializing default tasks:', error);
  }
};