name: Create Issue Branch

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: read

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create feature branch from issue
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branchName: feature/${{ github.event.issue.number }}-${{ github.event.issue.title }}
          separator: "-"
          autoCloseIssue: false
