name: Create Issue Branch

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: read

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create feature branch from issue
        uses: peter-evans/create-issue-branch@v5
        with:
          prefix: feature/
          separator: '-'
